Hidden folder when trying to make changes
m4tt72/terminal pull request #44
Opened 2023-01-29 16:30 UTC by miguelgargallo

There is a hidden folder that do not allows anyone to change files inside Hidden folder when trying to make changes Relates with #43

2023-01-30 11:15 UTC, m4tt72 commented
Hello @miguelgargallo, thanks for the contribution.

I'm not sure what you're trying to achieve in this PR? Could you please provide more information?

2023-01-31 18:35 UTC, miguelgargallo commented
Yes, in gitignore there is included /bin, when you try to git clone and deploy and change anything inside the same folder as "bin", it shows you an error not finding "bin" on deploy

2023-02-03 11:45 UTC, m4tt72 commented
@miguelgargallo please provide more info

2023-02-05 13:40 UTC, m4tt72 commented
@miguelgargallo the description of this PR is confusing, but I think I stumbled upon the same issue that you faced. The reason why there's a `bin` in `.gitignore` is because I have some scripts inside the `bin` folder that don't necessarily have to make it to the repo, as a consequence to that, the `src/utils/bin` also gets ignored. So as a solution, I suggest you don't remove the `bin` from `.gitignore` but instead either:

1. Change the `bin/` to `/bin/` so git only ignores any folder called `bin` in root dir.
2. Exclude `src/utils/bin` in `.gitignore`

Thanks for your submission.

2023-02-05 13:41 UTC, m4tt72 requested changes

2023-02-05 13:41 UTC, m4tt72 commented on .gitignore
> -bin/
instead of removing this line, you need to change it to `/bin/`

2023-02-13 10:25 UTC, m4tt72 commented
Closing the PR because [a fix](https://github.com/m4tt72/terminal/pull/45) was necessary and this PR went stale

2023-02-13 10:25 UTC, closed without merging